name: hospedagem_temporada
description: Exercício Flutter — Busca e Filtragem de Imóveis com IoC via Provider

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

flutter:
  uses-material-design: true
